### ISSUE TITLE
KeyError when calling get_comment(self, comment_id, **kwargs)

### ISSUE THREAD

**Issue by and-le** [Frameio/python-frameio-client#18]
A KeyError is raised whenever the get_comment(self, comment_id, **kwargs) method is called. The line of code below causes the error.

    endpoint = '/comments/{id}'.format(comment_id) 

Removing the "id" from the curly braces solves the problem.

**Comment by jhodges10** [comment]
Good catch, that addressed in #35 along with lots of other things!
