### ISSUE TITLE
update_asset(self, asset_id, **kwargs) error

### ISSUE THREAD

**Issue by and-le** [Frameio/python-frameio-client#19]
The endpoint for the `update_asset(self, asset_id, **kwargs)` method is incorrect.

Currently it is:
`endpoint = '/assets/{}/children'.format(asset_id)`

which raises a `requests.exceptions.HTTPError: 404 Client Error`

The correct endpoint should remove `/children` and is:

`endpoint = '/assets/{}'.format(asset_id)`

**Comment by jhodges10** [comment]
This is also addressed in #35. Good catch!
