### ISSUE TITLE
Pagination is not supported

### ISSUE THREAD

**Issue by humberthardy** [Frameio/python-frameio-client#20]
## How to reproduce:

Add the parameter `per_page` to a call (for example `get_asset_children(id, page_size=1)`), This parameter is passed inside the payload (not the GET parameter) and it returns a page_size of 50.

Moreover the ` PaginatedResponse` class is not able to load next and previous pages.

**Comment by jhodges10** [comment]
I'm going to start working on that this week @humberthardy. 

You're totally right in that pagination is a mess in this client wrapper (it might work if you use it right) but I'm going to make it much better!

**Comment by jhodges10** [comment]
The latest **0.8.1** release has vastly improved pagination support, courtesy of @strombergdev and #56. 

Closing.
